#!/usr/bin/env python3
"""Answer the supervisory question from the repository, in seconds.

    Which production changes in Q2 touched control SEC-API-01, which of them were
    agent-authored, at what autonomy tier, and who approved each one?

Playbook §6.2 calls being able to answer this in minutes rather than a week "the single
highest-value output of this whole programme". It works because the artifact header is
machine-readable and the gates emit evidence as they run — not because anyone
reconstructed anything afterwards.

    python scripts/query_evidence.py --control SEC-API-01 --quarter 2026Q2

DEMO DATA. The evidence records in this repository are produced by this repository's own
pipeline against a synthetic service. They are not any institution's audit records.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
from datetime import datetime

sys.path.insert(0, __file__.rsplit("/", 1)[0])

import artifacts  # noqa: E402
import gate  # noqa: E402

BANNER = (
    "DEMO DATA — generated by this repository's own pipeline against a synthetic "
    "service. Not an audit record of any institution."
)


def quarter_of(when: datetime) -> str:
    return f"{when.year}Q{(when.month - 1) // 3 + 1}"


def commits_for(path: pathlib.Path) -> list[dict]:
    """Git is the timestamp authority for repository artifacts (§6.3)."""
    out = subprocess.run(
        ["git", "log", "--follow", "--format=%H%x1f%aI%x1f%an%x1f%ae", "--", str(path)],
        cwd=gate.ROOT,
        capture_output=True,
        text=True,
    )
    commits = []
    for line in out.stdout.strip().split("\n"):
        if not line:
            continue
        sha, when, name, email = line.split("\x1f")
        commits.append({"sha": sha, "when": when, "author": name, "email": email})
    return commits


def evidence_records() -> list[dict]:
    """Individual gate results.

    bundle.json is an aggregate of these rather than one of them, so it carries no
    control_id and is skipped — keyed on the field this function needs rather than
    on the filename, so a future aggregate does not break the query the same way.
    """
    records = []
    for path in sorted((gate.ROOT / "evidence").glob("*.json")):
        try:
            record = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        if isinstance(record, dict) and "control_id" in record:
            records.append(record)
    return records


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--control", help="Control objective id, e.g. SEC-API-01")
    parser.add_argument("--quarter", help="e.g. 2026Q2")
    parser.add_argument("--risk-class", choices=["R1", "R2", "R3"])
    parser.add_argument("--agent-authored", action="store_true")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args()

    controls = {c["id"]: c for c in gate.load_yaml("policy/controls.yaml")["controls"]}
    if args.control and args.control not in controls:
        print(f"unknown control {args.control}. Known: {sorted(controls)}", file=sys.stderr)
        return 2

    records = evidence_records()
    rows = []

    for artifact in artifacts.all_artifacts():
        if artifact.stage != "plan" or artifact.errors:
            continue
        header = artifact.header

        if args.control and args.control not in header.get("controls", []):
            continue
        if args.risk_class and header.get("risk_class") != args.risk_class:
            continue

        commits = commits_for(artifact.path)
        first = commits[-1] if commits else None
        when = datetime.fromisoformat(first["when"]) if first else None
        if args.quarter and (not when or quarter_of(when) != args.quarter):
            continue

        # Agent-authored is a fact about identity, not an inference about style.
        authors = {c["email"] for c in commits}
        agent_identity = header.get("agent_identity", "")
        agent_authored = any(agent_identity in a or "[bot]" in a for a in authors)
        if args.agent_authored and not agent_authored:
            continue

        gates_run = [
            {
                "control": r["control_id"],
                "gate": r["gate"],
                "result": r["result"],
                "when": r["timestamp"],
            }
            for r in records
            if not args.control or r["control_id"] == args.control
        ]

        rows.append(
            {
                "change_id": header["change_id"],
                "risk_class": header["risk_class"],
                "autonomy_tier": header["autonomy_tier"],
                "controls": header.get("controls", []),
                "data_classification": header.get("data_classification"),
                "originator": header.get("originator"),
                "agent_identity": agent_identity,
                "model_route": header.get("model_route"),
                "agent_authored": agent_authored,
                "itsm_record": header.get("itsm_record"),
                "first_commit": first,
                "quarter": quarter_of(when) if when else None,
                "commits": len(commits),
                "approvers": sorted(a for a in authors if a != agent_identity),
                "gates": gates_run,
                "chain": sorted(artifacts.chain(header["change_id"])),
            }
        )

    if args.json:
        print(json.dumps({"disclaimer": BANNER, "query": vars(args), "results": rows}, indent=2))
        return 0

    print(f"\n  {BANNER}\n")
    scope = args.control or "all controls"
    print(f"  Query: {scope}" + (f", {args.quarter}" if args.quarter else "") + "\n")
    if not rows:
        print("  No changes match.\n")
        return 0

    for row in rows:
        print(
            f"  {row['change_id']}  {row['risk_class']}/{row['autonomy_tier']}"
            f"  {'agent-authored' if row['agent_authored'] else 'human-authored'}"
        )
        print(f"      originator   {row['originator']}")
        print(f"      agent        {row['agent_identity']}  route {row['model_route']}")
        print(f"      chain        {' -> '.join(row['chain'])}")
        print(f"      controls     {', '.join(row['controls'])}")
        if row["itsm_record"]:
            print(f"      ITSM         {row['itsm_record']}")
        passed = sum(1 for g in row["gates"] if g["result"] == "pass")
        print(f"      gates        {passed}/{len(row['gates'])} passed")
        print(f"      approvers    {', '.join(row['approvers']) or '(none recorded)'}")
        print()

    print(f"  {len(rows)} change(s). Answered from the repository, no reconstruction.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
